# Jekyll configuration

name: ""
description: ""
# URL strony (możesz zmienić na swój adres)
url: "https://artur-piernikarczyk.github.io"
# Ścieżka bazowa (jeśli strona jest w podfolderze)
baseurl: ""

# Ustawienia builda

markdown: kramdown
theme: jekyll-theme-cayman

# Wyklucz katalogi
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
